import { test, expect } from '@playwright/test';
import { installJourney } from '../support/journey.mjs';
for(const width of [390,1440])test(`English manager journey from signup to replay and results at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:960});
  const fixture=await installJourney(page),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const fits=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto('/signup');
  await expect(page.getByRole('heading',{name:'Welcome to the peloton'})).toBeVisible();
  await fits();await page.screenshot({path:`test-results/journey-signup-${width}.png`,fullPage:true});
  await page.getByLabel('Email',{exact:true}).fill('ui-test@example.invalid');
  await page.getByLabel('Password',{exact:true}).fill('only-a-local-ui-fixture');
  await page.getByRole('button',{name:'Create account →'}).click();
  await expect(page).toHaveURL(/\/onboarding$/);
  await page.getByLabel('Team name').fill('Northern Lights Cycling');
  await page.screenshot({path:`test-results/journey-onboarding-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Create my team →'}).click();
  await expect(page).toHaveURL(/\/team$/);
  await expect(page.locator('.club-rider')).toHaveCount(8);
  await page.getByRole('button',{name:'Women',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Freja Møller'})).toBeVisible();
  await page.getByRole('button',{name:'Men',exact:true}).click();
  await page.getByRole('link',{name:'Riders',exact:true}).click();
  await expect(page.locator('.club-rider')).toHaveCount(8);
  await fits();
  await page.getByRole('link',{name:'My team',exact:true}).click();
  await page.getByRole('link',{name:'Race details and lineup ↗'}).click();
  await page.getByRole('button',{name:/The Coast Classic/}).click();
  await expect(page.getByText('Your lineup',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Enter team',exact:true})).toBeDisabled();
  await fits();await page.screenshot({path:`test-results/journey-calendar-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Select the first eight'}).click();
  await expect(page.getByRole('button',{name:'Enter team',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Choose captain',exact:true}).first().click();
  await expect(page.getByRole('button',{name:'Enter team',exact:true})).toBeEnabled();
  fixture.rejectNextSave();
  await page.getByRole('button',{name:'Enter team',exact:true}).click();
  await expect(page.getByText('Could not save your lineup. Please try again.')).toBeVisible();
  expect(fixture.entry()).toBeNull();
  await page.getByRole('button',{name:'Enter team',exact:true}).click();
  await expect(page.getByText('Saved ✓',{exact:true})).toBeVisible();
  expect(fixture.entry().selected_riders).toHaveLength(8);
  expect(fixture.entry().selected_riders).toContain(fixture.entry().captain_id);
  await page.reload();await page.getByRole('button',{name:/The Coast Classic/}).click();
  await expect(page.getByText('Saved ✓',{exact:true})).toBeVisible();
  await fits();await page.screenshot({path:`test-results/journey-lineup-${width}.png`,fullPage:true});
  fixture.finish();
  await page.reload();await page.getByRole('button',{name:'Finished',exact:true}).click();
  await page.getByRole('button',{name:/The Coast Classic/}).click();
  await expect(page.getByRole('button',{name:'Enter team',exact:true})).toHaveCount(0);
  await page.getByRole('link',{name:'Results',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Watch the race first?'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Team results',exact:true})).toHaveCount(0);
  await page.getByRole('link',{name:'Watch the race →',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Race commentary'})).toBeVisible();
  await expect(page.getByRole('heading',{name:/wins/})).toHaveCount(0);
  await page.getByRole('button',{name:'▶ Play'}).click();
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByRole('button',{name:'Next moment →'}).click();
  await fits();await page.screenshot({path:`test-results/journey-replay-${width}.png`,fullPage:true});
  await page.getByRole('slider',{name:'Playback position'}).focus();await page.keyboard.press('End');
  await expect(page.getByText('The race is decided',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'View results and points →'}).click();
  await expect(page.getByRole('heading',{name:'Team results',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Rider results',exact:true})).toBeVisible();
  await fits();await page.screenshot({path:`test-results/journey-results-${width}.png`,fullPage:true});
  expect(errors).toEqual([]);
});
