import {test,expect} from '@playwright/test';

for(const width of [390,1440])test(`manager runs a recorded Motor Lab race at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const endpoint='http://localhost:3100/api/motor-lab';
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},data:{plan:'sprint',seed:1}})).status()).toBe(401);
 await page.goto('/login');
 // Use separate fixture managers so both viewport journeys respect the
 // read-only preview endpoint's per-user run limit.
 await page.getByLabel('Email or username').fill(width===390?'alice':'bob');
 await page.getByLabel('Password',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page).toHaveURL(/\/team$/);
 await page.getByRole('link',{name:'Motor Lab'}).click();
 await expect(page.getByRole('heading',{name:'Motor Lab'})).toBeVisible();
 expect((await context.request.post(endpoint,{headers:{Origin:'https://another.example'},data:{plan:'sprint',seed:1}})).status()).toBe(403);
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},
  data:{plan:'sprint',seed:1,orders:{breakWork:'freewheel'}}})).status()).toBe(400);
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},
  data:{plan:'sprint',seed:1,routeId:'unknown'}})).status()).toBe(400);
 await page.getByRole('radio',{name:/Send the captain ahead/}).check();
 await page.getByLabel('React to a dangerous break').selectOption('chase_if_threatened');
 await page.getByLabel('If Amber reaches a break').selectOption('sit_on');
 await page.getByLabel('From the 120 km marker').selectOption('hard');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByRole('heading',{name:'Coast Road laboratory'})).toBeVisible();
 await expect(page.getByText(/Committed orders: chase a threatening break · follow the plan for chase work · sit on in a break · ride hard after 120 km/)).toBeVisible();
 await expect(page.getByText('1 / 160',{exact:true})).toBeVisible();
 await expect(page.getByText(/The largest recorded gap is/)).toBeVisible();
 await page.getByRole('button',{name:/Play replay/}).click();
 await expect(page.locator('.motor-scoreboard strong').first()).not.toHaveText('1 / 160');
 await page.getByRole('button',{name:'Pause replay'}).click();
 const slider=page.getByRole('slider',{name:'Inspect recorded kilometre'});
 await slider.focus();await page.keyboard.press('End');
 await expect(page.getByText('160 / 160',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Previous moment'}).click();
 await expect(page.getByRole('listitem').filter({hasText:'Amber Captain'}).first()).toBeVisible();
 await page.getByLabel('React to a dangerous break').selectOption('hold_plan');
 await page.getByLabel('If Amber reaches a break').selectOption('cooperate');
 await page.getByLabel('From the 120 km marker').selectOption('follow_plan');
 await page.getByLabel('If Amber Captain is in a break').selectOption('40');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/attempt an attack from the break after 40 km/)).toBeVisible();
 await page.getByRole('button',{name:/41 km Amber Captain attacked from a break/}).click();
 await expect(page.locator('.motor-scoreboard strong').nth(1)).toHaveText('2');
 await expect(page.locator('.motor-timeline-trailing')).not.toHaveCount(0);
 await expect(page.locator('.motor-road article').first().getByText('1.0 s to Group 2')).toBeVisible();
 await expect(page.locator('.motor-road article').nth(1).getByText('4.6 s to peloton')).toBeVisible();
 await page.getByLabel('React to a dangerous break').selectOption('chase_if_threatened');
 await page.getByLabel("Road captain's leadership").selectOption('experienced');
 await page.getByRole('radio',{name:/Save energy/}).check();
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/experienced road captain/)).toBeVisible();
 await expect(page.getByText(/Amber road captain called a chase/).first()).toBeVisible();
 await page.getByRole('radio',{name:/Protect the sprinter/}).check();
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText('Amber rode Protect the sprinter')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Same scenario, two decisions'})).toBeVisible();
 await expect(page.getByRole('table').getByRole('rowheader',{name:'Amber Captain',exact:true})).toBeVisible();
 await expect(page.getByRole('row',{name:/Amber Captain in a break/})).toBeVisible();
 await expect(page.getByRole('row',{name:/Largest break advantage/})).toBeVisible();
 await page.getByLabel('React to a dangerous break').selectOption('hold_plan');
 await page.getByLabel('Peloton chase contribution').selectOption('ignore');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/hold chase helpers back/)).toBeVisible();
 await expect(page.getByRole('row',{name:/Amber chase kilometres/}).getByRole('cell').last()).toHaveText('0');
 await page.getByLabel('Laboratory route').selectOption('ridge');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByRole('heading',{name:'Ridge Road laboratory'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Same scenario, two decisions'})).toHaveCount(0);
 await expect(page.getByText(/Highest point: 490 m/)).toBeVisible();
 const ridgeSlider=page.getByRole('slider',{name:'Inspect recorded kilometre'});
 await ridgeSlider.focus();await page.keyboard.press('Home');
 for(let step=0;step<34;step++)await page.keyboard.press('ArrowRight');
 await expect(page.getByText(/At 35 km: 330 m elevation, \+5\.0% gradient/)).toBeVisible();
 await page.getByLabel('Peloton chase contribution').selectOption('follow_plan');
 await page.getByLabel('If Amber Captain is in a break').selectOption('none');
 await page.getByLabel("Road captain's leadership").selectOption('standard');
 await page.getByRole('button',{name:'Run the race'}).click();
 await page.getByLabel('Help a dropped captain').selectOption('drop_back_if_dropped');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/Committed orders:.*send a reachable helper back to a dropped captain/)).toBeVisible();
 await expect(page.getByRole('row',{name:/Amber Captain behind the peloton/}).getByRole('cell').last()).toHaveText('2 km');
 await expect(page.getByText(/helped Amber Captain recover/).first()).toBeVisible();
 await page.getByLabel('Laboratory route').selectOption('coast');
 await page.getByRole('button',{name:'Run the race'}).click();
 const waitingSlider=page.getByRole('slider',{name:'Inspect recorded kilometre'});
 await waitingSlider.fill('21');
 await expect(page.getByText('22 / 160',{exact:true})).toBeVisible();
 await expect(page.getByText('Waiting while the gap remains manageable: Amber, Birch')).toBeVisible();
 await expect(page.getByText('Teams with riders ahead: Cedar, Dune')).toBeVisible();
 await page.screenshot({path:`test-results/motor-lab-${width}.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
