import {test,expect} from '@playwright/test';

for(const width of [390,1440])test(`manager runs a recorded Motor Lab race at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const endpoint='http://localhost:3100/api/motor-lab';
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},data:{plan:'sprint',seed:1}})).status()).toBe(401);
 await page.goto('/login');
 await page.getByLabel('Email or username').fill('alice');
 await page.getByLabel('Password',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page).toHaveURL(/\/team$/);
 await page.getByRole('link',{name:'Motor Lab'}).click();
 await expect(page.getByRole('heading',{name:'Motor Lab'})).toBeVisible();
 expect((await context.request.post(endpoint,{headers:{Origin:'https://another.example'},data:{plan:'sprint',seed:1}})).status()).toBe(403);
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},
  data:{plan:'sprint',seed:1,orders:{breakWork:'freewheel'}}})).status()).toBe(400);
 expect((await context.request.post(endpoint,{headers:{Origin:'http://localhost:3100'},
  data:{plan:'sprint',seed:1,routeId:'unknown'}})).status()).toBe(400);
 await page.getByRole('radio',{name:/Send the captain ahead/}).check();
 await page.getByLabel('React to a dangerous break').selectOption('chase_if_threatened');
 await page.getByLabel('If Amber reaches a break').selectOption('sit_on');
 await page.getByLabel('From the 120 km marker').selectOption('hard');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByRole('heading',{name:'Coast Road laboratory'})).toBeVisible();
 await expect(page.getByText(/Committed orders: chase a threatening break · sit on in a break · ride hard after 120 km/)).toBeVisible();
 await expect(page.getByText('1 / 160',{exact:true})).toBeVisible();
 await expect(page.getByText(/The largest recorded gap is/)).toBeVisible();
 await page.getByRole('button',{name:/Play replay/}).click();
 await expect(page.locator('.motor-scoreboard strong').first()).not.toHaveText('1 / 160');
 await page.getByRole('button',{name:'Pause replay'}).click();
 const slider=page.getByRole('slider',{name:'Inspect recorded kilometre'});
 await slider.focus();await page.keyboard.press('End');
 await expect(page.getByText('160 / 160',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Previous moment'}).click();
 await expect(page.getByRole('listitem').filter({hasText:'Amber Captain'}).first()).toBeVisible();
 await page.getByLabel('React to a dangerous break').selectOption('hold_plan');
 await page.getByLabel('If Amber reaches a break').selectOption('cooperate');
 await page.getByLabel('From the 120 km marker').selectOption('follow_plan');
 await page.getByLabel('If Amber Captain is in a break').selectOption('40');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/attempt an attack from the break after 40 km/)).toBeVisible();
 await page.getByRole('button',{name:/41 km Amber Captain attacked from a break/}).click();
 await expect(page.locator('.motor-scoreboard strong').nth(1)).toHaveText('2');
 await page.getByLabel('React to a dangerous break').selectOption('chase_if_threatened');
 await page.getByLabel("Road captain's leadership").selectOption('experienced');
 await page.getByRole('radio',{name:/Save energy/}).check();
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText(/experienced road captain/)).toBeVisible();
 await expect(page.getByText(/Amber road captain called a chase/).first()).toBeVisible();
 await page.getByRole('radio',{name:/Protect the sprinter/}).check();
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByText('Amber rode Protect the sprinter')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Same scenario, two decisions'})).toBeVisible();
 await expect(page.getByRole('table').getByRole('row',{name:/Amber Captain/})).toBeVisible();
 await page.getByLabel('Laboratory route').selectOption('ridge');
 await page.getByRole('button',{name:'Run the race'}).click();
 await expect(page.getByRole('heading',{name:'Ridge Road laboratory'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Same scenario, two decisions'})).toHaveCount(0);
 await page.screenshot({path:`test-results/motor-lab-${width}.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
