import { test, expect } from "@playwright/test";
for (const width of [390, 1440]) test(`visual studio profiles, comparison and local kit at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 960 });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/login');
  await page.getByLabel('Email or username').fill('alice');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/team$/);
  await page.getByRole('button', { name: 'View profile of Emil Berg', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Emil Berg' })).toBeVisible();
  await page.screenshot({ path: `test-results/studio-profile-${width}.png` });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'View profile of Emil Berg', exact: true })).toBeFocused();
  for (const name of ['Emil Berg', 'Louis Morel', 'Mateo Rojas']) await page.getByRole('button', { name: `Compare ${name}`, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Compare Dawit Tesfay', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Compare selected riders', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Compare riders' })).toBeVisible();
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(11);
  await page.screenshot({ path: `test-results/studio-comparison-${width}.png` });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Women', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Selected riders' })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('mountain');
  await expect(page.locator('.club-rider')).toHaveCount(5);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('all');
  await page.getByRole('link', { name: 'Club identity', exact: true }).click();
  const paletteButtons=page.locator('.studio-palette-options button');
  await expect(paletteButtons).toHaveCount(4);
  const paletteNames=await paletteButtons.allTextContents();
  const chosenPalette=paletteNames[1];
  await paletteButtons.nth(1).click();
  const patternSelect=page.getByLabel('Jersey pattern', {exact:false});
  await expect(patternSelect.locator('option')).toHaveCount(3);
  const chosenPattern=await patternSelect.locator('option').nth(1).getAttribute('value');
  await patternSelect.selectOption(chosenPattern);
  await page.getByRole('button', { name: 'Save local preview' }).click();
  await expect(page.getByRole('status')).toContainText('Preview saved in this browser');
  await page.reload();
  await expect(page.getByRole('button', { name: chosenPalette, exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Jersey pattern')).toHaveValue(chosenPattern);
  await page.locator('.supporter-kit-studio summary').click();
  await expect(page.getByLabel('Custom jersey layout').locator('option')).toHaveCount(25);
  for(const layout of await page.getByLabel('Custom jersey layout').locator('option').evaluateAll(nodes=>nodes.map(n=>n.value))) {
    await page.getByLabel('Custom jersey layout').selectOption(layout);
    await expect(page.getByRole('img',{name:'Custom supporter jersey preview'})).toBeVisible();
  }
  await page.getByLabel('Main colour', {exact:true}).fill('#123456');
  await expect(page.getByLabel('Jersey pattern')).toHaveValue(chosenPattern);
  await page.screenshot({ path: `test-results/studio-kit-${width}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Back to my team' }).click();
  await expect(page.locator('.club-rider')).toHaveCount(8);
  await page.screenshot({ path: `test-results/studio-squad-${width}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Email or username').fill('bob');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/team$/);
  await page.getByRole('link', { name: 'Club identity', exact: true }).click();
  await expect(page.locator('.studio-palette-options button')).toHaveCount(4);
  expect(await page.locator('.studio-palette-options button').allTextContents()).not.toEqual(paletteNames);
  await expect(page.locator('.studio-palette-options button').first()).toHaveAttribute('aria-pressed','true');
  expect(errors).toEqual([]);
});
