import { test, expect } from "@playwright/test";
for (const width of [390, 1440]) test(`released profiles, comparison and atlas at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 960 });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/login');
  await page.getByLabel('Email or username').fill('alice');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/team$/);
  await page.getByRole('button', { name: 'View profile of Emil Berg', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Emil Berg' })).toBeVisible();
  await page.screenshot({ path: `test-results/studio-profile-${width}.png` });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'View profile of Emil Berg', exact: true })).toBeFocused();
  for (const name of ['Emil Berg', 'Louis Morel', 'Mateo Rojas']) await page.getByRole('button', { name: `Compare ${name}`, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Compare Dawit Tesfay', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Compare selected riders', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Compare riders' })).toBeVisible();
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(11);
  await expect(page.getByRole('dialog').locator('tbody tr').filter({hasText:'Fatigue'}).locator('td').first()).toHaveClass('studio-best-value');
  await page.screenshot({ path: `test-results/studio-comparison-${width}.png` });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Women', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Selected riders' })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('mountain');
  await expect(page.locator('.club-rider')).toHaveCount(5);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('all');
  await expect(page.locator('.game-date .club-badge')).toBeVisible();
  await page.getByRole('link',{name:'Atlas',exact:true}).click();
  await page.getByText('Find a place',{exact:true}).click();
  await page.getByLabel('Search the atlas').fill('Northern Plateau');
  await expect(page.locator('.atlas-directory-results button')).toHaveCount(1);
  await page.getByRole('button',{name:'Visit Northern Plateau',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Northern Plateau',exact:true})).toBeVisible();
  await expect(page.getByRole('region',{name:'Place notes'})).toContainText('regular snow');
  await page.screenshot({path:`test-results/studio-atlas-${width}.png`,fullPage:true});
  await page.getByLabel('Search the atlas').fill('no-such-place');
  await expect(page.getByText('No places match. Try another name or place type.')).toBeVisible();
  await page.goto('/');
  await page.getByText('Do I need to be online during the race?',{exact:true}).click();
  await expect(page.getByText('No. Choose your lineup and orders before the deadline. The whole race is calculated before you watch its replay.')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
