import { test, expect } from "@playwright/test";
for (const width of [390, 1440]) test(`visual studio profiles, comparison and local kit at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 960 });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/login');
  await page.getByLabel('Email or username').fill('alice');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/team$/);
  await page.getByRole('button', { name: 'View profile of Emil Berg', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Emil Berg' })).toBeVisible();
  await page.screenshot({ path: `test-results/studio-profile-${width}.png` });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'View profile of Emil Berg', exact: true })).toBeFocused();
  for (const name of ['Emil Berg', 'Louis Morel', 'Mateo Rojas']) await page.getByRole('button', { name: `Compare ${name}`, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Compare Dawit Tesfay', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Compare selected riders', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Compare riders' })).toBeVisible();
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(11);
  await page.screenshot({ path: `test-results/studio-comparison-${width}.png` });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Women', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Selected riders' })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('mountain');
  await expect(page.locator('.club-rider')).toHaveCount(5);
  await page.getByRole('combobox', { name: 'Specialty', exact: true }).selectOption('all');
  await page.getByRole('link', { name: 'Club identity', exact: true }).click();
  await page.getByRole('button', { name: 'Ocean & coral', exact: true }).click();
  await page.getByLabel('Jersey pattern').selectOption('diagonal');
  await page.getByRole('button', { name: 'Save local preview' }).click();
  await expect(page.getByRole('status')).toContainText('Preview saved in this browser');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Ocean & coral', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Jersey pattern')).toHaveValue('diagonal');
  await page.screenshot({ path: `test-results/studio-kit-${width}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Back to my team' }).click();
  await expect(page.locator('.club-rider')).toHaveCount(8);
  await page.screenshot({ path: `test-results/studio-squad-${width}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Email or username').fill('bob');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/team$/);
  await page.getByRole('link', { name: 'Club identity', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Forest & honey', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Jersey pattern')).toHaveValue('band');
  expect(errors).toEqual([]);
});
