"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import TeamShell from "../../components/TeamShell";
import AtlasDirectory, { PlaceNotes } from "../../components/AtlasDirectory";
import { atlasWorld } from "../../../lib/world/atlas-data.mjs";
import { clampCamera, detailLevel, fitBounds, geometryBounds, geometryPath, intersects, labelsFor, objectCamera, visibleRepresentations, zoomCamera } from "../../../lib/world/atlas-view.mjs";
import "./atlas.css";
const objects=atlasWorld.objects, index=new Map(objects.map(o=>[o.id,o]));
const initial=fitBounds([15,0,465,355],1.04);
const styles={land:['#c8cf9a','#e8dcab',0],forest:['#69855b','none',1],upland:['#a5ac7e','none',1],grass:['#b6c583','none',1],mountain:['#9b9582','none',1],volcanic:['#aa8d72','none',1],steppe:['#d3c38c','none',1],desert:['#cc9a70','none',1],ice:['#e9e8d8','#c3d4cc',2],water:['#75aeb0','#5c929d',8],river:['none','#6c9da3',8],ridge:['none','#8c795c',5],canyon:['none','#9e664e',5],'city-area':['#e9debe','#c8b991',5],district:['url(#atlas-urban)','#f4edcf',6],park:['url(#atlas-garden)','#748e63',11],road:['none','#fff2d0',9],precinct:['#ece0c2','#bbaa7f',10],building:['#b89069','#775c43',12],plaza:['url(#atlas-paving)','#b6a284',11],runway:['#90927e','#6e725e',12],relief:['#807f69','#e3deba',2],woodland:['#456e50','none',2],footpath:['none','#fff2d0',13],roof:['none','#6d5942',13]};
function Shape({geometry,...props}){if(geometry.type==='Point')return <circle cx={geometry.coordinates[0]} cy={geometry.coordinates[1]} {...props}/>;if(geometry.type==='MultiPoint')return <g>{geometry.coordinates.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} {...props}/>)}</g>;return <path d={geometryPath(geometry)} {...props}/>;}
export default function Atlas(){
  const [camera,setCamera]=useState(initial),[selected,setSelected]=useState('WORLD-001'),[trail,setTrail]=useState([]),[earth,setEarth]=useState(false),[cell,setCell]=useState('I10'),[pixelWidth,setPixelWidth]=useState(1000);
  const svg=useRef(null),pointers=useRef(new Map()),dragged=useRef(false);
  const level=detailLevel(camera.width),chosen=index.get(selected),unit=camera.width/pixelWidth;
  const visible=useMemo(()=>visibleRepresentations(objects,camera),[camera]);
  const labels=useMemo(()=>labelsFor(visible,camera,pixelWidth),[visible,camera,pixelWidth]);
  const parentChain=[];let ancestor=chosen;while(ancestor&&ancestor.id!=='EARTH-001'){parentChain.unshift(ancestor);ancestor=index.get(ancestor.parentId);}
  function select(id){const o=index.get(id),next=o&&objectCamera(o);if(!next)return;setTrail(t=>[...t,{camera,selected}]);setSelected(id);setCamera(clampCamera(next));setEarth(false);}
  function back(){const last=trail.at(-1);if(last){setCamera(last.camera);setSelected(last.selected);setTrail(t=>t.slice(0,-1));}}
  useEffect(()=>{const observer=new ResizeObserver(entries=>setPixelWidth(entries[0].contentRect.width||1000));observer.observe(svg.current);return()=>observer.disconnect();},[]);
  useEffect(()=>{const el=svg.current;function wheel(e){e.preventDefault();const b=el.getBoundingClientRect();setCamera(v=>zoomCamera(v,e.deltaY>0?1.18:1/1.18,[(e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height]));}el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
  function down(e){if(e.button!==0&&e.pointerType==='mouse')return;dragged.current=false;pointers.current.set(e.pointerId,[e.clientX,e.clientY]);}
  function move(e){const ps=pointers.current,old=ps.get(e.pointerId);if(!old)return;const next=[e.clientX,e.clientY],b=svg.current.getBoundingClientRect();if(Math.hypot(next[0]-old[0],next[1]-old[1])>2){dragged.current=true;e.currentTarget.setPointerCapture(e.pointerId);}const other=[...ps.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){const before=Math.hypot(old[0]-other[0],old[1]-other[1]),after=Math.hypot(next[0]-other[0],next[1]-other[1]);if(after>0)setCamera(v=>zoomCamera(v,before/after,[(next[0]+other[0])/2/b.width-b.left/b.width,(next[1]+other[1])/2/b.height-b.top/b.height]));}else setCamera(v=>clampCamera({...v,x:v.x-(next[0]-old[0])/b.width*v.width,y:v.y-(next[1]-old[1])/b.height*v.width*.75}));ps.set(e.pointerId,next);}
  function up(e){pointers.current.delete(e.pointerId);}
  function key(e){if(e.target!==e.currentTarget)return;const delta=camera.width*.12;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home'){setCamera(initial);setSelected('WORLD-001');}else if(e.key==='+'||e.key==='=')setCamera(v=>zoomCamera(v,.7));else if(e.key==='-')setCamera(v=>zoomCamera(v,1/.7));else setCamera(v=>clampCamera({...v,x:v.x+(e.key==='ArrowRight'?delta:e.key==='ArrowLeft'?-delta:0),y:v.y+(e.key==='ArrowDown'?delta:e.key==='ArrowUp'?-delta:0)}));}}
  const nearby=objects.filter(o=>o.id!==selected&&o.geometry&&o.type!=='grid_cell'&&!o.properties.reserved&&(o.parentId===selected||(chosen.type==='grid_cell'&&intersects(geometryBounds(o.geometry),geometryBounds(chosen.geometry))&&o.type!=='region'&&o.id!=='WORLD-001')));
  const scaleKm=camera.width<1?.1:camera.width<5?.5:camera.width<30?5:camera.width<100?10:50;
  return <TeamShell compact><header className="atlas-heading"><div><p className="atlas-eyebrow">A WORLD TO DISCOVER</p><h1>Pelotonia Atlas</h1><p>From sweeping landscapes to hidden corners.</p></div><button className="btn" onClick={()=>setEarth(v=>!v)} aria-expanded={earth}>Earth context ↗</button></header>
    {earth&&<section className="atlas-earth"><svg viewBox="0 0 240 160" role="img" aria-label="Schematic Earth context: Pelotonia in the South Pacific"><circle cx="110" cy="80" r="72" fill="#507d87"/><ellipse cx="110" cy="80" rx="35" ry="72" fill="none" stroke="#acc4bd"/><path d="M39 80H181M47 48H174M48 112H174" stroke="#acc4bd"/><path d="M53 87L64 80 76 88 85 84 92 106 78 117 61 110Z M100 111L106 120 100 129M109 102L113 108" fill="#c8c998"/><circle cx="140" cy="109" r="4" fill="#f5d599"/><text x="146" y="105" fill="#fff5dc" fontSize="10">Pelotonia</text></svg><div><h2>An island nation in the South Pacific</h2><p>Pelotonia is a fictional part of Earth. This placement is schematic; its precise Earth coordinates are still undecided. The atlas uses local kilometres.</p><button className="btn" onClick={()=>{setEarth(false);select('WORLD-001');}}>Explore the islands</button></div></section>}
    <section className="studio-atlas-discover" aria-label="Discover Pelotonia"><div><p className="identity-eyebrow">THE FIELD GUIDE</p><h2>Every place has a story.</h2><p>Explore the existing atlas, from island landscapes to Aurelia’s cathedral quarter.</p></div><div className="studio-atlas-picks">{objects.filter(o=>['WORLD-001','AUR-LMK-001'].includes(o.id) || (o.type==='settlement' && o.name==='Aurelia')).map(o=><button className="btn" key={o.id} onClick={()=>select(o.id)}>{o.name} ↗</button>)}</div></section>
    <AtlasDirectory objects={objects} onSelect={select}/>
    <nav className="atlas-breadcrumb" aria-label="Atlas navigation"><button disabled={!trail.length} onClick={back}>← Back</button>{parentChain.map(o=><button key={o.id} onClick={()=>select(o.id)} aria-current={o.id===selected?'location':undefined}>{o.name||o.id}</button>)}</nav>
    <div className="atlas-layout"><section className="atlas-map-wrap" aria-label="Interactive atlas"><div className="atlas-map-tools"><button aria-label="Zoom in" onClick={()=>setCamera(v=>zoomCamera(v,.65))}>+</button><button aria-label="Zoom out" onClick={()=>setCamera(v=>zoomCamera(v,1/.65))}>−</button><button aria-label="Show the whole island" onClick={()=>select('WORLD-001')}>⌂</button></div>
      <svg ref={svg} className="atlas-map" viewBox={`${camera.x} ${camera.y} ${camera.width} ${camera.width*.75}`} role="group" aria-label="Map of Pelotonia. Use arrow keys to pan and plus or minus to zoom." tabIndex={0} onKeyDown={key} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>
        <defs><radialGradient id="atlas-sea"><stop offset="0" stopColor="#83aeb0"/><stop offset="1" stopColor="#326578"/></radialGradient><clipPath id="atlas-land"><path d={geometryPath(index.get('WORLD-001').geometry)}/></clipPath><pattern id="atlas-grain" width="5" height="5" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".13" fill="#4b5432" opacity=".15"/></pattern><pattern id="atlas-urban" width=".26" height=".22" patternUnits="userSpaceOnUse"><rect width=".26" height=".22" fill="#ddceb0"/><rect x=".025" y=".025" width=".17" height=".13" rx=".015" fill="#c9bc9f"/><path d="M.23 0V.22M0 .19H.26" stroke="#f3e8d0" strokeWidth=".018"/></pattern><pattern id="atlas-garden" width=".035" height=".035" patternUnits="userSpaceOnUse"><rect width=".035" height=".035" fill="#acbc86"/><circle cx=".013" cy=".013" r=".008" fill="#809966"/></pattern><pattern id="atlas-paving" width=".02" height=".02" patternUnits="userSpaceOnUse"><rect width=".02" height=".02" fill="#d8c8a6"/><path d="M0 0H.02V.02" fill="none" stroke="#baa988" strokeWidth=".001"/></pattern></defs>
        <rect x={camera.x} y={camera.y} width={camera.width} height={camera.width*.75} fill="url(#atlas-sea)"/>
        {visible.filter(r=>r.style!=='region-label').sort((a,b)=>(styles[a.style]?.[2]??11)-(styles[b.style]?.[2]??11)).map(r=>{const s=styles[r.style],isPoint=r.geometry.type==='Point',clickable=Boolean(r.object.name)&&r.object.type!=='river_system';return <Shape key={r.key} geometry={r.geometry} fill={s?.[0]||'#f5e6bc'} stroke={selected===r.object.id?'#825a24':s?.[1]||'#375c49'} strokeWidth={selected===r.object.id?2:r.style==='road'?2.5:r.style==='river'?2:1} vectorEffect="non-scaling-stroke" r={unit*(r.style==='capital'?5.5:3.5)} clipPath={['forest','upland','grass','mountain','volcanic','steppe','desert','relief','woodland'].includes(r.style)?'url(#atlas-land)':undefined} opacity={r.style==='woodland'?.55:r.style==='relief'?.6:r.object.type==='region'?.7:1} role={clickable?'button':undefined} tabIndex={clickable?0:undefined} aria-label={clickable?`Explore ${r.object.name}`:undefined} onClick={clickable?()=>{if(!dragged.current)select(r.object.id);}:undefined} onKeyDown={clickable?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();select(r.object.id);}}:undefined} style={{cursor:clickable?'pointer':undefined,paintOrder:isPoint?'stroke':undefined}}/>;})}
        {level<=2&&<path d={geometryPath(index.get('WORLD-001').geometry)} fill="url(#atlas-grain)" pointerEvents="none"/>}
        {labels.map(r=>{const b=geometryBounds(r.geometry),x=(b[0]+b[2])/2,y=(b[1]+b[3])/2;return <text key={r.key} x={x} y={y-unit*8} textAnchor="middle" fontSize={unit*(r.style==='region-label'?13:11)} fontFamily="Bricolage, sans-serif" fill={r.style==='region-label'?'#46543b':'#253f36'} stroke="#f1ecd3" strokeWidth={unit*2.5} paintOrder="stroke" pointerEvents="none">{r.object.name}</text>;})}
        <g pointerEvents="none"><path d={`M${camera.x+camera.width*.04} ${camera.y+camera.width*.71}h${scaleKm}`} stroke="#fff5df" strokeWidth="2" vectorEffect="non-scaling-stroke"/><text x={camera.x+camera.width*.04} y={camera.y+camera.width*.695} fontSize={unit*12} fill="#fff5df">{scaleKm<1?`${scaleKm*1000} m`:`${scaleKm} km`}</text><text x={camera.x+camera.width*.95} y={camera.y+camera.width*.05} fontSize={unit*16} fill="#fff5df">N ↑</text></g>
      </svg><div className="atlas-map-caption"><span>{['','Whole country','Landscapes and macro areas','Districts and local places','Buildings, squares, and gardens'][level]}</span><span>Drag · zoom · choose a place</span></div>
    </section><aside className="atlas-panel"><p className="atlas-eyebrow">{chosen.type==='grid_cell'?'MACRO AREA':'SELECTED PLACE'}</p><h2>{chosen.name||'Name pending'}</h2><p className="atlas-prototype">Geographic prototype · editable working names</p>{chosen.properties.population&&<p className="atlas-population">≈ {chosen.properties.population.value.toLocaleString('en-GB')} residents{chosen.properties.populationScope==='metropolitan'?' in the metropolitan area':''}</p>}{chosen.type==='grid_cell'&&<p>{index.get(chosen.properties.regionId)?.name||'Sea area'}. This area currently has landscape-level detail only.</p>}{selected==='AUR-LMK-001'&&<p>188 × 92 m · central spire 171 m · precinct approximately 35 ha. Around 45 m above the river.</p>}<PlaceNotes place={chosen}/><div className="atlas-place-list">{nearby.filter(o=>o.type!=='region').sort((a,b)=>(a.type==='settlement'?0:1)-(b.type==='settlement'?0:1)).map(o=><button key={o.id} onClick={()=>select(o.id)}>{o.name||'Unnamed natural feature'} <span>↗</span></button>)}</div>{selected==='WORLD-001'&&<p className="small">Start with Aurelia to explore its districts, Old Aurelia, and the cathedral.</p>}
      <form className="atlas-grid-form" onSubmit={e=>{e.preventDefault();select(`GRID-${cell}`);}}><label htmlFor="atlas-cell">Explore a macro area</label><div><select id="atlas-cell" value={cell} onChange={e=>setCell(e.target.value)}>{objects.filter(o=>o.type==='grid_cell').map(o=><option key={o.id} value={o.name}>{o.name} · {index.get(o.properties.regionId)?.name||'Sea'}</option>)}</select><button className="btn" type="submit">Show</button></div></form>
    </aside></div><footer className="atlas-footer"><div><span className="atlas-key forest"/>Forest & wetlands <span className="atlas-key mountain"/>Highlands & mountains <span className="atlas-key desert"/>Drylands <span className="atlas-key water"/>Water</div><p>Outlines, locations, and city geometry are design proposals. Details outside Aurelia are provisional. No cycling routes have been added.</p></footer>
  </TeamShell>;
}
